name: show status

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}-${{ inputs.concurrency_key }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      test:
        required: false
        type: string
        default: test
      concurrency_key:
        required: false
        type: string
        default: qa
      ref:
        required: false
        type: string
        default: ${{ github.sha }}

defaults:
  run:
    shell: bash -l {0}

jobs:
  print-status:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub
        run: echo '${{ toJSON(github) }}'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Dump GitHub
        run: ls -la && exit 1
