name: Manual Branch Merge

on:
  workflow_dispatch: 
    inputs:
     branches:
      description: "Branches to merge"
      type: string

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Create New Branch
        id: create-branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          INPUT_BRANCHES="${{ github.event.inputs.branches }}"
          INPUT_BRANCHES="$(echo -e "${INPUT_BRANCHES}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          NEW_BRANCH_NAME="merged-branches-${{ github.ref_name }}-$TIMESTAMP"
          BASE_BRANCH=${{ github.ref_name }}
          ACCESS_TOKEN="$GH_TOKEN"
          REPO_NAME=${{ github.repository }}

          # Create a new branch using the GitHub API
          curl -X POST \
            -H "Authorization: token $ACCESS_TOKEN" \
            -d '{
              "ref": "refs/heads/'$NEW_BRANCH_NAME'",
              "sha": "'$(curl -s -H "Authorization: token $ACCESS_TOKEN" https://api.github.com/repos/$REPO_NAME/git/refs/heads/$BASE_BRANCH | jq -r '.object.sha')'"
            }' \
            "https://api.github.com/repos/$REPO_NAME/git/refs"

          echo "New branch name: $NEW_BRANCH_NAME"
          echo "Input branches: $INPUT_BRANCHES"
        continue-on-error: false

      # - name: Merge Branches
      #   run: |
      #     INPUT_BRANCHES=${{ github.event.inputs.branches }}
      #     for BRANCH in $INPUT_BRANCHES
      #     do
      #       # Merge branches using the GitHub API and `gh` CLI
      #       gh api -X PUT "repos/$GITHUB_REPOSITORY/merges" -F base="$NEW_BRANCH_NAME" -F head="$BRANCH"
      #       if [ $? -ne 0 ]
      #       then
      #         echo "Merge conflict or failure detected. Deleting the new branch."
      #         git push origin --delete $NEW_BRANCH_NAME
      #         exit 1
      #       fi
      #     done
      #     echo "All branches merged successfully."

      # - name: Push Merged Branch
      #   run: |
      #     git push origin $NEW_BRANCH_NAME
      #     echo "Merged branch pushed to the repository."
