name: Create Issue on New Release
on:
  workflow_dispatch:
jobs:
  create-issue:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ""
      RELEASE_HTML_URL: ""
      RELEASE_PUBLISHED_AT: ""
      RELEASE_BODY: ""
    steps:
      - name: Get Latest Release Info
        run: |
          latest_release=$(curl --silent "https://api.github.com/repos/external-secrets/external-secrets/releases/latest")
          export RELEASE_TAG=$(echo ${latest_release} | jq -r .tag_name)
          echo "RELEASE_TAG=$(echo ${latest_release} | jq -r .tag_name)" >> $GITHUB_OUTPUT
          export RELEASE_HTML_URL=$(echo ${latest_release} | jq -r .html_url)
          export RELEASE_PUBLISHED_AT=$(echo ${latest_release} | jq -r .published_at)
          export RELEASE_BODY=$(echo ${latest_release} | jq -r .body)
      - name: Create Issue
        run: |
          issue_title="New external-secrets release: ${{ env.RELEASE_TAG }}"
          issue_body=$(cat <<EOF
          A new version of external-secrets has been released.

          Release information:
          - Tag: ${{ env.RELEASE_TAG }}
          - URL: ${{ env.RELEASE_HTML_URL }}
          - Date: ${{ env.RELEASE_PUBLISHED_AT }}
          - Body: ${{ env.RELEASE_BODY }}
          EOF
                    )
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -d '{"title":"${issue_title}","body":"${{ env.RELEASE_HTML_URL }}"}' \
               -X POST "https://api.github.com/repos/knkarthik/action-test/issues"
