name: Production Deploy


on:
  push:
    branches:
      - "main"

  workflow_dispatch: 
    inputs:
      deploy:
        description: "Check this to perform production deploy"
        type: boolean

jobs:
  
  build-and-test:
    if: ${{ github.event_name == 'push' }}
    secrets: inherit
    uses: ./.github/workflows/build-and-test.yml
    with:
      concurrency_key: ${{ github.run_id }}

  build-base:
    # if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'true' && github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    concurrency: 
     group: production-build-base-${{ github.run_id }}
     cancel-in-progress: false
    steps:
      - run: echo '${{ toJSON(github) }}'

  production-ember-build:
    # if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'true' && github.ref_name == 'main' }}
    needs: [build-base]
    concurrency: 
      group: production-ember-build-${{ github.run_id }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploying" && sleep 5

  production-deploy:
    # if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'true' && github.ref_name == 'main' }}
    
    needs: [production-ember-build]
    runs-on: ubuntu-latest
    environment: 
      name: prod
      url: "${{ steps.prod-deploy.outputs.URL }}.example.com"
    concurrency: 
      group: production-deploy
      cancel-in-progress: false
    steps:
      - name: prod deploy
        id: prod-deploy
        run: echo "URL=prod" >> $GITHUB_OUTPUT