name: Schedule
run-name: test

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'env'
        required: true
        type: string
  schedule:
    - cron: "*/6 * * * *"
env:
  env_name: ${{ github.event_name == 'schedule' && 'all' || '' }}

jobs:
  scaleup-qa:
    runs-on: ubuntu
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Scale
        uses: ./.github/actions/scale
        with:
          env_name: ${{ env.env_name }}
