name: Schedule
run-name: test

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'env'
        required: true
        type: string
  schedule:
    - cron: "0 7 * * 1-5"
# env:
#   env_name: ${{ github.event_name == 'schedule' && 'all' || '' }}

jobs:
  scaleup-qa:
    runs-on: ubuntu-latest
    if: ${{ inputs.env_name != '' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Scale
        uses: ./.github/actions/scale
        with:
          env_name: ${{ inputs.env_name }}
  scaleup-qa-2:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Scale
          uses: ./.github/actions/scale
          with:
            env_name: ${{ inputs.env_name }}
