name: test-arc
on:
  push:
    branches:
      - kn-test-arc

jobs:
  single-job:
    runs-on: [self-hosted,centah]
    steps:
      - run: echo "🎉 This job uses runner scale set runners!"
  parallel-job:
    runs-on: centah
    strategy:
      matrix:
        version: [ 10, 12, 14 ]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
